export const icons = {
    home: 'pi pi-home',
    register: 'pi pi-user-plus',
    employees: 'pi pi-briefcase',
    reports: 'pi pi-file',
    tasks: 'pi pi-list',
    clients: 'pi pi-users',
    admin: 'pi pi-cog',
    user: 'pi pi-user',
    file: 'pi-file',
    profile: 'pi-id-card',
    search: 'pi pi-search',
    comment: 'pi-comments',
    communications: 'pi pi-phone',
    clock: 'pi pi-clock',
    favorite: 'pi pi-star',
    manager: 'pi pi-graduation-cap',
    export: 'pi pi-file-export',
    calendar: 'pi pi-calendar'
  };